"""empty message

Revision ID: 6f36d69aaf23
Revises: 
Create Date: 2020-08-29 12:44:38.770974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f36d69aaf23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administration',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_administration'))
    )
    op.create_table('attachment',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cdn_link', sa.TEXT(), nullable=False),
    sa.Column('format', sa.String(length=100), nullable=False),
    sa.Column('validate', sa.Integer(), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment'))
    )
    op.create_table('configuration',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.Text(), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration'))
    )
    op.create_table('exercise',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise'))
    )
    op.create_table('history',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_history'))
    )
    op.create_table('lesson',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson'))
    )
    op.create_table('library',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library'))
    )
    op.create_table('newsletter',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter'))
    )
    op.create_table('permission',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('alias', sa.String(length=150), nullable=True),
    sa.Column('function', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission')),
    sa.UniqueConstraint('name', name=op.f('uq_permission_name'))
    )
    op.create_table('profile',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile'))
    )
    op.create_table('school_class',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_class'))
    )
    op.create_table('school_discipline',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_discipline'))
    )
    op.create_table('school_grade',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_grade'))
    )
    op.create_table('school_net',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_net'))
    )
    op.create_table('school_period',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('begin', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_period'))
    )
    op.create_table('type_parameter',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_type_parameter'))
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('born', sa.Date(), nullable=True),
    sa.Column('salt', sa.String(length=40), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('salt', name=op.f('uq_user_salt'))
    )
    op.create_table('administration_school_net',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('administration_id', sa.String(length=36), nullable=False),
    sa.Column('school_network_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['administration_id'], ['administration.id'], name=op.f('fk_administration_school_net_administration_id_administration')),
    sa.ForeignKeyConstraint(['school_network_id'], ['school_net.id'], name=op.f('fk_administration_school_net_school_network_id_school_net')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_administration_school_net'))
    )
    op.create_table('configuration_profile',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('configuration_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configuration.id'], name=op.f('fk_configuration_profile_configuration_id_configuration')),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_configuration_profile_profile_id_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_profile'))
    )
    op.create_table('exercise_item',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_exercise_item_exercise_id_exercise')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_item'))
    )
    op.create_table('integrations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('administration_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['administration_id'], ['administration.id'], name=op.f('fk_integrations_administration_id_administration')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations'))
    )
    op.create_table('lesson_attachment',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('attachment_id', sa.String(length=36), nullable=False),
    sa.Column('main_attachment', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], name=op.f('fk_lesson_attachment_attachment_id_attachment')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name=op.f('fk_lesson_attachment_lesson_id_lesson')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_attachment'))
    )
    op.create_table('library_attachment',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('library_id', sa.String(length=36), nullable=False),
    sa.Column('attachment_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], name=op.f('fk_library_attachment_attachment_id_attachment')),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], name=op.f('fk_library_attachment_library_id_library')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_attachment'))
    )
    op.create_table('parameters',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('type_parameter_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['type_parameter_id'], ['type_parameter.id'], name=op.f('fk_parameters_type_parameter_id_type_parameter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parameters'))
    )
    op.create_table('person',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('born', sa.Date(), nullable=False),
    sa.Column('document', sa.String(length=11), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_person_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person'))
    )
    op.create_table('profile_permission',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name=op.f('fk_profile_permission_permission_id_permission')),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_profile_permission_profile_id_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_permission'))
    )
    op.create_table('profile_user',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_profile_user_profile_id_profile')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_profile_user_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_user'))
    )
    op.create_table('school_unit',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('school_net_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['school_net_id'], ['school_net.id'], name=op.f('fk_school_unit_school_net_id_school_net')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_unit'))
    )
    op.create_table('ticket',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('response_of', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('administration_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['administration_id'], ['administration.id'], name=op.f('fk_ticket_administration_id_administration')),
    sa.ForeignKeyConstraint(['response_of'], ['ticket.id'], name=op.f('fk_ticket_response_of_ticket')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket'))
    )
    op.create_table('administrator',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('administration_id', sa.String(length=36), nullable=False),
    sa.Column('profile_user_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['administration_id'], ['administration.id'], name=op.f('fk_administrator_administration_id_administration')),
    sa.ForeignKeyConstraint(['profile_user_id'], ['profile_user.id'], name=op.f('fk_administrator_profile_user_id_profile_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_administrator'))
    )
    op.create_table('exercise_item_choice',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('exercise_item_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['exercise_item_id'], ['exercise_item.id'], name=op.f('fk_exercise_item_choice_exercise_item_id_exercise_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_item_choice'))
    )
    op.create_table('integrations_tokens',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('integrations_id', sa.String(length=36), nullable=False),
    sa.Column('validate', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['integrations_id'], ['integrations.id'], name=op.f('fk_integrations_tokens_integrations_id_integrations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations_tokens'))
    )
    op.create_table('message',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('to', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=150), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name=op.f('fk_message_lesson_id_lesson')),
    sa.ForeignKeyConstraint(['to'], ['profile_user.id'], name=op.f('fk_message_to_profile_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_table('newsletter_profile_user',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('newsletter_id', sa.String(length=36), nullable=False),
    sa.Column('profile_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletter.id'], name=op.f('fk_newsletter_profile_user_newsletter_id_newsletter')),
    sa.ForeignKeyConstraint(['profile_user_id'], ['profile_user.id'], name=op.f('fk_newsletter_profile_user_profile_user_id_profile_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_profile_user'))
    )
    op.create_table('school_net_administrator',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('school_net_id', sa.String(length=36), nullable=False),
    sa.Column('profile_user_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['profile_user_id'], ['profile_user.id'], name=op.f('fk_school_net_administrator_profile_user_id_profile_user')),
    sa.ForeignKeyConstraint(['school_net_id'], ['school_net.id'], name=op.f('fk_school_net_administrator_school_net_id_school_net')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_net_administrator'))
    )
    op.create_table('school_unit_profile_users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('school_unit_id', sa.String(length=36), nullable=False),
    sa.Column('profile_user_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['profile_user_id'], ['profile_user.id'], name=op.f('fk_school_unit_profile_users_profile_user_id_profile_user')),
    sa.ForeignKeyConstraint(['school_unit_id'], ['school_unit.id'], name=op.f('fk_school_unit_profile_users_school_unit_id_school_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_unit_profile_users'))
    )
    op.create_table('ticket_attachment',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('integrations_id', sa.String(length=36), nullable=False),
    sa.Column('attachment_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], name=op.f('fk_ticket_attachment_attachment_id_attachment')),
    sa.ForeignKeyConstraint(['integrations_id'], ['integrations.id'], name=op.f('fk_ticket_attachment_integrations_id_integrations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_attachment'))
    )
    op.create_table('unit_grade',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('school_grade_id', sa.String(length=36), nullable=False),
    sa.Column('school_unit_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['school_grade_id'], ['school_grade.id'], name=op.f('fk_unit_grade_school_grade_id_school_grade')),
    sa.ForeignKeyConstraint(['school_unit_id'], ['school_unit.id'], name=op.f('fk_unit_grade_school_unit_id_school_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unit_grade'))
    )
    op.create_table('discipline_grade',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('unit_grade_id', sa.String(length=36), nullable=False),
    sa.Column('school_discipline_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['school_discipline_id'], ['school_discipline.id'], name=op.f('fk_discipline_grade_school_discipline_id_school_discipline')),
    sa.ForeignKeyConstraint(['unit_grade_id'], ['unit_grade.id'], name=op.f('fk_discipline_grade_unit_grade_id_unit_grade')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discipline_grade'))
    )
    op.create_table('unit_grade_library',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('library_id', sa.String(length=36), nullable=False),
    sa.Column('unit_grade_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], name=op.f('fk_unit_grade_library_library_id_library')),
    sa.ForeignKeyConstraint(['unit_grade_id'], ['unit_grade.id'], name=op.f('fk_unit_grade_library_unit_grade_id_unit_grade')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unit_grade_library'))
    )
    op.create_table('discipline_period',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('discipline_grade_id', sa.String(length=36), nullable=False),
    sa.Column('school_period_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['discipline_grade_id'], ['discipline_grade.id'], name=op.f('fk_discipline_period_discipline_grade_id_discipline_grade')),
    sa.ForeignKeyConstraint(['school_period_id'], ['school_period.id'], name=op.f('fk_discipline_period_school_period_id_school_period')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discipline_period'))
    )
    op.create_table('classes_discipline',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('discipline_period_id', sa.String(length=36), nullable=False),
    sa.Column('school_class_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['discipline_period_id'], ['discipline_period.id'], name=op.f('fk_classes_discipline_discipline_period_id_discipline_period')),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_class.id'], name=op.f('fk_classes_discipline_school_class_id_school_class')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes_discipline'))
    )
    op.create_table('activity',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('begin', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('obrigatory', sa.Boolean(), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes_discipline.id'], name=op.f('fk_activity_class_id_classes_discipline')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity'))
    )
    op.create_table('lesson_classes_discipline',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('classes_discipline_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('begin', sa.Date(), nullable=True),
    sa.Column('hour', sa.String(length=15), nullable=True),
    sa.Column('validate', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['classes_discipline_id'], ['classes_discipline.id'], name=op.f('fk_lesson_classes_discipline_classes_discipline_id_classes_discipline')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name=op.f('fk_lesson_classes_discipline_lesson_id_lesson')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_classes_discipline'))
    )
    op.create_table('student_discipline',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('classes_discipline_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['classes_discipline_id'], ['classes_discipline.id'], name=op.f('fk_student_discipline_classes_discipline_id_classes_discipline')),
    sa.ForeignKeyConstraint(['student_id'], ['profile_user.id'], name=op.f('fk_student_discipline_student_id_profile_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_discipline'))
    )
    op.create_table('teacher_discipline',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('classes_discipline_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['classes_discipline_id'], ['classes_discipline.id'], name=op.f('fk_teacher_discipline_classes_discipline_id_classes_discipline')),
    sa.ForeignKeyConstraint(['teacher_id'], ['profile_user.id'], name=op.f('fk_teacher_discipline_teacher_id_profile_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_discipline'))
    )
    op.create_table('activity_attachment',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('attachment_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_activity_attachment_activity_id_activity')),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], name=op.f('fk_activity_attachment_attachment_id_attachment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_attachment'))
    )
    op.create_table('activity_exercise',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('rate', sa.DECIMAL(), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_activity_exercise_activity_id_activity')),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_activity_exercise_exercise_id_exercise')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_exercise'))
    )
    op.create_table('activity_student',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('begin', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_activity_student_activity_id_activity')),
    sa.ForeignKeyConstraint(['student_id'], ['profile_user.id'], name=op.f('fk_activity_student_student_id_profile_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_student'))
    )
    op.create_table('annotation',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('lesson_classes_discipline_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['lesson_classes_discipline_id'], ['lesson_classes_discipline.id'], name=op.f('fk_annotation_lesson_classes_discipline_id_lesson_classes_discipline')),
    sa.ForeignKeyConstraint(['student_id'], ['student_discipline.id'], name=op.f('fk_annotation_student_id_student_discipline')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotation'))
    )
    op.create_table('student_lesson_classes_discipline',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('lesson_classes_discipline_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['lesson_classes_discipline_id'], ['lesson_classes_discipline.id'], name=op.f('fk_student_lesson_classes_discipline_lesson_classes_discipline_id_lesson_classes_discipline')),
    sa.ForeignKeyConstraint(['student_id'], ['student_discipline.id'], name=op.f('fk_student_lesson_classes_discipline_student_id_student_discipline')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_lesson_classes_discipline'))
    )
    op.create_table('activity_student_attachment',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_attr', sa.JSON(), nullable=True),
    sa.Column('activity_student_id', sa.String(length=36), nullable=False),
    sa.Column('attachment_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['activity_student_id'], ['activity_student.id'], name=op.f('fk_activity_student_attachment_activity_student_id_activity_student')),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], name=op.f('fk_activity_student_attachment_attachment_id_attachment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_student_attachment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_student_attachment')
    op.drop_table('student_lesson_classes_discipline')
    op.drop_table('annotation')
    op.drop_table('activity_student')
    op.drop_table('activity_exercise')
    op.drop_table('activity_attachment')
    op.drop_table('teacher_discipline')
    op.drop_table('student_discipline')
    op.drop_table('lesson_classes_discipline')
    op.drop_table('activity')
    op.drop_table('classes_discipline')
    op.drop_table('discipline_period')
    op.drop_table('unit_grade_library')
    op.drop_table('discipline_grade')
    op.drop_table('unit_grade')
    op.drop_table('ticket_attachment')
    op.drop_table('school_unit_profile_users')
    op.drop_table('school_net_administrator')
    op.drop_table('newsletter_profile_user')
    op.drop_table('message')
    op.drop_table('integrations_tokens')
    op.drop_table('exercise_item_choice')
    op.drop_table('administrator')
    op.drop_table('ticket')
    op.drop_table('school_unit')
    op.drop_table('profile_user')
    op.drop_table('profile_permission')
    op.drop_table('person')
    op.drop_table('parameters')
    op.drop_table('library_attachment')
    op.drop_table('lesson_attachment')
    op.drop_table('integrations')
    op.drop_table('exercise_item')
    op.drop_table('configuration_profile')
    op.drop_table('administration_school_net')
    op.drop_table('user')
    op.drop_table('type_parameter')
    op.drop_table('school_period')
    op.drop_table('school_net')
    op.drop_table('school_grade')
    op.drop_table('school_discipline')
    op.drop_table('school_class')
    op.drop_table('profile')
    op.drop_table('permission')
    op.drop_table('newsletter')
    op.drop_table('library')
    op.drop_table('lesson')
    op.drop_table('history')
    op.drop_table('exercise')
    op.drop_table('configuration')
    op.drop_table('attachment')
    op.drop_table('administration')
    # ### end Alembic commands ###
